Repository NOW-SOPT-APP6-BUBBLE/bubble-Server, pull requests merged in 2024-05, with the labels that each got.

#7 [feature] #5 - 엔티티 생성
  src/main/java/com/sopt/mobile/domain/Artist.java
  src/main/java/com/sopt/mobile/domain/ArtistMember.java
  src/main/java/com/sopt/mobile/domain/BaseTime.java
  src/main/java/com/sopt/mobile/domain/Discount.java
  src/main/java/com/sopt/mobile/domain/Member.java
  src/main/java/com/sopt/mobile/domain/SubscribedArtist.java
  src/main/java/com/sopt/mobile/domain/TempClass.java
Labels: ➕ add, 👊🏻 PULL REQUEST, 의진

#12 [feat] #8 양방향 매핑 추가
  src/main/java/com/sopt/mobile/MobileApplication.java
  src/main/java/com/sopt/mobile/domain/Artist.java
  src/main/java/com/sopt/mobile/domain/ArtistMember.java
  src/main/java/com/sopt/mobile/domain/Member.java
Labels: ✨ feature, 👊🏻 PULL REQUEST, 서진

#14 [feature] #2 아티스트 조회(친구목록) API 구현
  build.gradle
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/ArtistMemberController.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberQuerydslRepository.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberQuerydslRepositoryImpl.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberRepository.java
  src/main/java/com/sopt/mobile/service/ArtistMemberService.java
  src/main/java/com/sopt/mobile/service/ArtistMemberServiceImpl.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistMemberFindDto.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistMemberListFindDto.java
Labels: ✨ feature, 👊🏻 PULL REQUEST, 서진

#15 feat : 서비스 제공인 아티스트 구분 #2
  src/main/java/com/sopt/mobile/repository/ArtistMemberQuerydslRepositoryImpl.java
Labels: ✨ feature, 👊🏻 PULL REQUEST, 서진

#16 [type] #9-아티스트 그룹 조회 API 구현
  src/main/generated/com/sopt/mobile/domain/QArtist.java
  src/main/generated/com/sopt/mobile/domain/QArtistMember.java
  src/main/generated/com/sopt/mobile/domain/QBaseTime.java
  src/main/generated/com/sopt/mobile/domain/QDiscount.java
  src/main/generated/com/sopt/mobile/domain/QMember.java
  src/main/generated/com/sopt/mobile/domain/QSubscribedArtist.java
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/ArtistController.java
  src/main/java/com/sopt/mobile/service/ArtistService.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistsFindListResponseDto.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistsFindResponseDto.java
  src/main/java/com/sopt/mobile/service/dto/response/TempClass.java
Labels: ➕ add, ✨ feature, 의진

#17 [feature] #3-즐겨찾기 삭제 구현
  .gitignore
  src/main/java/com/sopt/mobile/common/dto/ErrorMessage.java
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/ArtistMemberController.java
  src/main/java/com/sopt/mobile/controller/SubscribedArtistController.java
  src/main/java/com/sopt/mobile/repository/SubscribedArtistRepository.java
  src/main/java/com/sopt/mobile/service/ArtistMemberServiceImpl.java
  src/main/java/com/sopt/mobile/service/SubscribedArtistService.java
  src/main/java/com/sopt/mobile/service/SubscribedArtistServiceImpl.java
Labels: ✨ feature, 👊🏻 PULL REQUEST, 서진

#19 [feature] : #10 - 아티스트 즐겨찾기 등록 API 구현
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/SubscribedArtistController.java
  src/main/java/com/sopt/mobile/domain/BaseTime.java
  src/main/java/com/sopt/mobile/service/SubscribedArtistService.java
  src/main/java/com/sopt/mobile/service/SubscribedArtistServiceImpl.java
Labels: ➕ add, ✨ feature, 의진

#18 [feature]-#4
  src/main/generated/com/sopt/mobile/domain/QArtist.java
  src/main/generated/com/sopt/mobile/domain/QArtistMember.java
  src/main/generated/com/sopt/mobile/domain/QBaseTime.java
  src/main/generated/com/sopt/mobile/domain/QDiscount.java
  src/main/generated/com/sopt/mobile/domain/QMember.java
  src/main/generated/com/sopt/mobile/domain/QSubscribedArtist.java
  src/main/java/com/sopt/mobile/common/dto/ErrorMessage.java
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/ArtistMemberController.java
  src/main/java/com/sopt/mobile/domain/Artist.java
  src/main/java/com/sopt/mobile/domain/ArtistMember.java
  src/main/java/com/sopt/mobile/domain/SubscribedArtist.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberQuerydslRepository.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberQuerydslRepositoryImpl.java
  src/main/java/com/sopt/mobile/repository/ArtistMemberRepository.java
  src/main/java/com/sopt/mobile/service/ArtistMemberService.java
  src/main/java/com/sopt/mobile/service/ArtistMemberServiceImpl.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistMemberDetailFindDto.java
Labels: ✨ feature, 👊🏻 PULL REQUEST, 서진

#20 [feature] #11 - 특정 아티스트 조회 API 구현
  src/main/java/com/sopt/mobile/common/dto/ErrorMessage.java
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/controller/ArtistController.java
  src/main/java/com/sopt/mobile/domain/Subscribe.java
  src/main/java/com/sopt/mobile/service/ArtistService.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistFindDto.java
  src/main/java/com/sopt/mobile/service/dto/response/ArtistFindResponseDto.java
Labels: ➕ add, ✨ feature, 👊🏻 PULL REQUEST, 의진

#25 [type] #11 - 상태코드 수정, 할인 적용 가격 수정 및 Subscribe 도메인 수정
  src/main/java/com/sopt/mobile/common/dto/SuccessMessage.java
  src/main/java/com/sopt/mobile/domain/Subscribe.java
  src/main/java/com/sopt/mobile/service/ArtistService.java
  src/test/java/com/sopt/mobile/ArtistServiceTest.java
Labels: ♻️ refactor, 🌏 deploy, ✅ test, 👊🏻 PULL REQUEST, 의진
